package com.beanit.asn1bean.compiler;

import com.beanit.asn1bean.ber.BerTag;
import com.beanit.asn1bean.compiler.model.*;
import com.beanit.asn1bean.util.HexString;

import java.io.BufferedWriter;
import java.io.File;
import java.io.IOException;
import java.io.Writer;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;

import static java.nio.charset.StandardCharsets.UTF_8;

public class BerGoLangStructWriter extends BerJavaClassWriter implements BerImplementationWriter {

  private static final String LIB_SRC = "github.com/kitandara/asn1ber";
  private static final String LIB_PREFIX = "asn1";
  private static final String GOLANG_VERSION = "1.23";

  public BerGoLangStructWriter(HashMap<String, AsnModule> modulesByName,
      String outputBaseDir,
      String basePackageName, boolean disableWritingVersion) {
    super(modulesByName, outputBaseDir, basePackageName, false, disableWritingVersion, false);

    if (this.basePackageName.endsWith(".")) {
      this.basePackageName = basePackageName.substring(0, basePackageName.length() - 1); // Remove added '.'
    }
  }

  @Override
  public void initOutputDir() throws IOException {
    // Write go.mod file
    Writer fileWriter = Files.newBufferedWriter(new File(outputBaseDir, "go.mod").toPath(), UTF_8);
    BufferedWriter bf = new BufferedWriter(fileWriter);
    bf.write("module " + this.basePackageName + "\n\n");
    bf.write("go " + GOLANG_VERSION + "\n");
    bf.close();
    fileWriter.close();
  }

  @Override
  protected String moduleToPackageName(String moduleName) {
    return Utils.moduleToPackageName(moduleName, "/");
  }

  @Override
  protected void writeClassHeader(String typeName, AsnModule module) throws IOException {
    //noinspection ResultOfMethodCallIgnored
    outputDirectory.mkdirs();

    Writer fileWriter =
        Files.newBufferedWriter(new File(outputDirectory, typeName + ".go").toPath(), UTF_8);
    out = new BufferedWriter(fileWriter);

    String versionString = "";
    if (insertVersion) {
      versionString = " v" + Compiler.VERSION;
    }

    write("/*");
    write(
        " * This class file was automatically generated by ASN1bean"
            + versionString
            + " (http://www.beanit.com)\n */\n");
    write("package " + basePackageName + "/" + Utils.lastPartOfPackageName(module.moduleIdentifier.name) + "\n");

    write("import (\n"
        + "\t\"encoding/hex\"\n"
        + "\t\"errors\"\n"
        + "\t\"fmt\"\n"
        + "\"bytes\"\n"
        + LIB_PREFIX + " \"" + LIB_SRC + "\"\n"
        + "\t\"io\"\n\n");

    // Import from others...
    List<String> importedClassesFromOtherModules = new ArrayList<>();

    for (SymbolsFromModule symbolsFromModule : module.importSymbolFromModuleList) {
      AsnModule importedModule = modulesByName.get(symbolsFromModule.modref);
      for (String importedSymbol : symbolsFromModule.symbolList) {
        if (Character.isUpperCase(importedSymbol.charAt(0))) {
          if (importedModule.typesByName.get(importedSymbol) != null) {
            importedClassesFromOtherModules.add(
                moduleToPackageName(importedModule.moduleIdentifier.name)
                    + "/"
                    + Utils.cleanUpName(importedSymbol)
            );
          }
        }
      }
    }
    Collections.sort(importedClassesFromOtherModules);
    for (String modulePackage : importedClassesFromOtherModules) {
      write("import \"" + basePackageName + "/" + modulePackage + "\"");
    }
    write(")");
  }

  private String getModuleForType(String assignedTypeName) {

    if (module.typesByName.get(assignedTypeName) != null) {
      return null; // Internal to the module
    }
    for (SymbolsFromModule symbolsFromModule : module.importSymbolFromModuleList) {
      for (String sym : symbolsFromModule.symbolList) {
        if (sym.equalsIgnoreCase(assignedTypeName)) {
          return symbolsFromModule.modref;
        }
      }
    }
    return LIB_PREFIX;
  }

  @Override
  String getBerTagParametersString(BerImplementationWriter.Tag tag) {
    return LIB_PREFIX + "."
        + tag.tagClass
        + "_CLASS, " + LIB_PREFIX + "."
        + tag.typeStructure.toString()
        + ", "
        + tag.value;
  }


  @Override
  protected void writeRetaggingTypeClass(
      String typeName, String assignedTypeName, AsnType typeDefinition, BerImplementationWriter.Tag tag)
      throws IOException {

    String embeddedType = Utils.cleanUpName(assignedTypeName); // The embedded type.

    // Output the struct
    write("type " + typeName + " struct {");
    String importModuleName = getModuleForType(typeDefinition.name);
    write((importModuleName != null ? importModuleName + "." : "") + "" + embeddedType);

    write("}\n");

    // Write tag func
    if (tag != null) {
      write("func (b *" + typeName + ") GetTag () {");
      write("return " + LIB_PREFIX + ".NewBerTag(" + getBerTagParametersString(tag) + ")");
      write("}");

      // Ignore constructors, go straight to encoder/decode funcs
      write("func (b *" + typeName + ") Encode(reverseOS io.Writer, withTagList ...bool) (int, error) {");
      write("var withTag bool\n"
          + "\tif len(withTagList) > 0 {\n"
          + "\t\twithTag = withTagList[0]\n"
          + "\t} else {\n"
          + "\t\twithTag = true\n"
          + "\t}");
      write("codeLength := 0");
      write("var err error\n"
          + "\tvar n int");
      if (tag.type == BerImplementationWriter.TagType.EXPLICIT) {
        if (isDirectAnyOrChoice((AsnTaggedType) typeDefinition)) {
          write("n,err = b." + embeddedType + " .Encode(reverseOS)");
        } else {
          write("n,err = b." + embeddedType + ".Encode(reverseOS, true)");
        }
        write("if err != nil {\n"
            + "\t\treturn codeLength, err\n"
            + "\t}");

        write("codeLength += n");
        write("n,err = " + LIB_PREFIX + ".EncodeLength(codeLength, reverseOS)");
        write("codeLength += n");

      } else {
        write("n,err = b." + embeddedType + ".Encode(reverseOS, false)");
      }
      write("if err != nil {\n"
          + "\t\treturn codeLength, err\n"
          + "\t}");

      write("if withTag {");
      write("n,err = b.GetTag().Encode(reverseOS)");
      write("codeLength += n");
      write("if err != nil {\n"
          + "\t\treturn codeLength, err\n"
          + "\t}");
      write("}\n");

      write("return codeLength,nil");
      write("}\n");

      // .. now write Decode
      write("func (b *" + typeName + ") Decode(is io.Reader, withTagList ...bool) (int, error) {");
      write("var withTag bool\n"
          + "\tif len(withTagList) > 0 {\n"
          + "\t\twithTag = withTagList[0]\n"
          + "\t} else {\n"
          + "\t\twithTag = true\n"
          + "\t}\n"
          + "\tcodeLength := 0");
      write("var err error\n"
          + "\tvar n int");
      write("if withTag {");
      write("n,err = b.GetTag().decodeAndCheck(is);");
      write("codeLength += n");
      write("if err != nil {\n"
          + "\t\t\treturn codeLength, err\n"
          + "\t\t}");
      write("}\n");

      if (tag.type == BerImplementationWriter.TagType.EXPLICIT) {

        write(" length := &" + LIB_PREFIX + ".BerLength{}");
        write(" n,err = length.Decode(is)\n");
        write("codeLength += n");
        write("if err != nil {\n"
            + "\t\t\treturn codeLength, err\n"
            + "\t\t}");
        if (isDirectAnyOrChoice((AsnTaggedType) typeDefinition)) {
          write("n,err = b." + embeddedType + ".DecodeWithTag(is, null);");
        } else {
          write("n,err = b. " + embeddedType + ".Decode(is, true)");
        }
        write("codeLength += n");
        write("if err != nil {\n"
            + "\t\t\treturn codeLength, err\n"
            + "\t\t}");
        write("n,err = length.ReadEocIfIndefinite(is)\n");
      } else {
        write("n,err = b. " + embeddedType + ".Decode(is, false)");
      }
      write("codeLength += n");
      write("if err != nil {\n"
          + "\t\t\treturn codeLength, err\n"
          + "\t\t}");

      write("return codeLength,nil");
      write("}\n");
    }
    write("}");
  }


private String normaliseClassName(String className) {
    String[] l = className.split("\\.");
    if (l.length > 1) {
      return l[l.length - 2] + "." + l[l.length - 1];
    }
    return className;
  }

  @Override
  protected void writeMembers(List<AsnElementType> componentTypes) throws IOException {

    for (AsnElementType element : componentTypes) {
      String className = normaliseClassName(element.className);
      String elementName = Utils.cleanUpName(element.name);
      write(elementName + " *" + className);
    }
    write("");
  }

  @Override
  protected void writeChoiceClass(
      String className,
      AsnChoice asn1TypeElement,
      BerImplementationWriter.Tag tag,
      String isStaticStr,
      List<String> listOfSubClassNames)
      throws IOException {
    List<AsnElementType> componentTypes = asn1TypeElement.componentTypes;

    addAutomaticTagsIfNeeded(componentTypes);

    writeSubClasses(className, listOfSubClassNames, componentTypes);
    setClassNamesOfComponents(listOfSubClassNames, componentTypes, className);

    write("type " + className + " struct {\n");
    writeMembers(componentTypes);
    write("}\n");

    if (tag != null) {
      write("func (b *" + className + ") GetTag () {");
      write("return " + LIB_PREFIX + ".NewBerTag(" + getBerTagParametersString(tag) + ")");
      write("}");
    }

    writeChoiceEncodeFunction(className, componentTypes, tag != null);

    writeChoiceDecodeMethod(className, convertToComponentInfos(componentTypes), tag != null);

    writeChoiceToStringFunction(className, componentTypes);
  }

  @Override
  protected void writeChoiceEncodeFunction(
      String className, List<AsnElementType> componentTypes, boolean hasExplicitTag) throws IOException {

    write("func (b *" + className + ") Encode(reverseOS io.Writer, withTagList ...bool) (int, error) {");
    if (!hasExplicitTag) {
      write("var withTag bool\n"
          + "\tif len(withTagList) > 0 {\n"
          + "\t\twithTag = withTagList[0]\n"
          + "\t} else {\n"
          + "\t\twithTag = true\n"
          + "\t}");
    }
    write("codeLength := 0");
    write("var err error\n"
        + "\tvar n int");
    for (int j = componentTypes.size() - 1; j >= 0; j--) {
      if (isExplicit(getTag(componentTypes.get(j)))) {
        write("var sublength int\n");
        break;
      }
    }

    for (int j = componentTypes.size() - 1; j >= 0; j--) {

      AsnElementType componentType = componentTypes.get(j);

      BerImplementationWriter.Tag componentTag = getTag(componentType);

      write("if b." + getVariableName(componentType) + " != nil) {");

      String explicitEncoding = getExplicitEncodingParameter(componentType);

      if (isExplicit(componentTag)) {
        write(
            "sublenth,err = b."
                + getVariableName(componentType)
                + ".Encode(reverseOS"
                + explicitEncoding
                + ")");
        write("codeLength += sublength");
        write("n,err = " + LIB_PREFIX + ".EncodeLength( sublength,reverseOS)");
      } else {
        write(
            "n,err = b."
                + getVariableName(componentType)
                + ".Encode(reverseOS"
                + explicitEncoding
                + ");");
      }

      write("codeLength += n");
      write("if err != nil {\n"
          + "\t\treturn codeLength, err\n"
          + "\t}");

      if (componentTag != null) {
        writeEncodeTag(componentTag);
      }

      if (hasExplicitTag) {
        write("n,err = " + LIB_PREFIX + ".EncodeLength( codeLength,reverseOS)");
        write("codeLength += n");
        write("if withTag {");
        write("n,err = b.GetTag().encode(reverseOS)");
        write("codeLength += n");
        write("}");
        write("if err != nil {\n"
            + "\t\treturn codeLength, err\n"
            + "\t}");
      }

      write("return codeLength,nil");
      write("}");

      write("");
    }

    write("return 0, errors.New(\"error encoding CHOICE: No element of CHOICE was selected.\");");

    write("}\n");
  }

  @Override
  protected void writeSimpleDecodeFunction(String className, String param) throws IOException {
    write("func (b *" + className + ") Decode(is io.Reader, withTagList ...bool) (int, error) {");
    write("return b.DecodeWithTag(is, " + param + ")");
    write("}\n");
  }

  @Override
  protected void writeChoiceDecodeMethod(String className, List<ComponentInfo> components, boolean hasExplicitTag)
      throws IOException {

    if (hasExplicitTag) {
      write("func (b *" + className + ") Decode(is io.Reader, withTagList ...bool) (int, error) {");
      write("var withTag bool\n"
          + "\tif len(withTagList) > 0 {\n"
          + "\t\twithTag = withTagList[0]\n"
          + "\t} else {\n"
          + "\t\twithTag = true\n"
          + "\t}\n"
          + "");
      write("var err error\n"
          + "\tvar n int");

      write(" tlvByteCount := 0");
      write("berTag := new (" + LIB_PREFIX + ".BerTag)\n");

      write("if withTag {");
      write("n,err = b.GetTag().DecodeAndCheck(is)");
      write("tlvByteCount += n");
      write("if err != nil {\n"
          + "\t\t\treturn codeLength, err\n"
          + "\t\t}");

      write("}\n");
      write(" explicitTagLength := &" + LIB_PREFIX + ".BerLength{}");

      write("n,err = explicitTagLength.Decode(is)");
      write("tlvByteCount += n");
      write("n,err = berTag.Decode(is)\n");
      write("tlvByteCount += n");
      write("if err != nil {\n"
          + "\t\t\treturn codeLength, err\n"
          + "\t\t}");
    } else {

      writeSimpleDecodeFunction(className, "null");

      write("func (b *" + className + ") DecodeWithTag(is io.Reader, berTag *" + LIB_PREFIX + ".BerTag) (int, error) {");
      write("var err error\n"
          + "\tvar n int");

      write("tlvByteCount := 0");
      write("tagWasPassed := (berTag != nil)\n");

      write("if berTag == nil {");
      write("berTag = new(" + LIB_PREFIX + ".BerTag)");
      write("n,err = berTag.Decode(is)");
      write("tlvByteCount += n");
      write("if err != nil {\n"
          + "\t\t\treturn codeLength, err\n"
          + "\t\t}");
      write("}\n");
    }

    if (containsUntaggedChoiceOrAny(components)) {
      write("var numDecodedBytes int\n");
    }

    for (ComponentInfo component : components) {
      if (component.isDirectChoiceOrAny && (component.tag == null)) {
        writeChoiceComponentDecodeUntaggedChoiceOrAny(component, hasExplicitTag);
      } else {
        writeChoiceComponentDecodeRegular(className, component, hasExplicitTag);
      }
    }

    if (!hasExplicitTag) {
      write("if tagWasPassed {");
      write("return 0,nil");
      write("}\n");
    }

    write(
        "return errors.New(fmt.Sprintf(\"Error decoding CHOICE: Tag %s matched to no item.\",berTag))");

    write("}\n");
  }

  @Override
  protected void writeChoiceComponentDecodeRegular(String className, ComponentInfo component, boolean taggedChoice)
      throws IOException {
    if (component.tag != null) {
      write("if berTag.Equals(" + getBerTagParametersString(component.tag) + ") {");
    } else {
      write("if berTag.EqualsTag(b." + component.className + ".GetTag()) {");
    }

    if (isExplicit(component.tag)) {
      write(" length := &" + LIB_PREFIX + ".BerLength{}");
      write(" n,err = length.Decode(is)\n");
      write("tlvByteCount += n");
      write("if err != nil {\n"
          + "\t\t\treturn 0, err\n"
          + "\t\t}");
    }

    write("b." + component.variableName + " = new (" + normaliseClassName(component.className) + ")");
    write(
        "n,err = "
            + component.variableName
            + ".Decode" + getDecodeFuncSuffix(component) + "(is, "
            + getDecodeTagParameter(component)
            + ")");
    write("tlvByteCount += n");
    if (isExplicit(component.tag)) {
      write("n,err = length.ReadEocIfIndefinite(is)");
      write("tlvByteCount += n");
      write("if err != nil {\n"
          + "\t\t\treturn 0, err\n"
          + "\t\t}");
    }
    if (taggedChoice) {
      write("n,err = explicitTagLength.ReadEocIfIndefinite(is)");
      write("tlvByteCount += n");
      write("if err != nil {\n"
          + "\t\t\treturn 0, err\n"
          + "\t\t}");
    }
    write("return tlvByteCount,nil");
    write("}\n");
  }

  @Override
  protected void writeChoiceComponentDecodeUntaggedChoiceOrAny(
      ComponentInfo component, boolean taggedChoice) throws IOException {
    write("b." + component.variableName + " = new (" + normaliseClassName(component.className) + ")");
    write(
        "numDecodedBytes,err = b."
            + component.variableName
            + ".Decode" + getDecodeFuncSuffix(component) + "(is, "
            + getDecodeTagParameter(component)
            + ")");

    write("if numDecodedBytes != 0 {");
    if (taggedChoice) {
      write("n,err = explicitTagLength.ReadEocIfIndefinite(is);");
      write("tlvByteCount += n");
    }
    write("return tlvByteCount + numDecodedBytes,nil");
    write("} else {");
    write("b." + component.variableName + " = nil");
    write("}\n");
  }

  @Override
  protected void writeSequenceOrSetClass(
      String className,
      AsnSequenceSet asnSequenceSet,
      BerImplementationWriter.Tag tag,
      String isStaticStr,
      List<String> listOfSubClassNames)
      throws IOException {

    List<AsnElementType> componentTypes = asnSequenceSet.componentTypes;
    addAutomaticTagsIfNeeded(componentTypes);
    setClassNamesOfComponents(listOfSubClassNames, componentTypes, className);
    writeSubClasses(className, listOfSubClassNames, componentTypes);

    write("type " + className + " struct {");
    writeMembers(componentTypes);
    write("}");

    BerImplementationWriter.Tag mainTag = tagFromSequenceSet(tag, asnSequenceSet.isSequence);

    // Write tag func.
    write("func (b *" + className + ") GetTag () {");
    write("return " + LIB_PREFIX + ".NewBerTag(" + getBerTagParametersString(mainTag) + ")");
    write("}");
    boolean hasExplicitTag = (tag != null) && (tag.type == BerImplementationWriter.TagType.EXPLICIT);

    writeSequenceOrSetEncodeFunction(className, componentTypes, hasExplicitTag, asnSequenceSet.isSequence);
    if (asnSequenceSet.isSequence) {
      writeSequenceDecodeMethod(className, convertToComponentInfos(componentTypes), hasExplicitTag);
    } else {
      writeSetDecodeFunction(className, convertToComponentInfos(componentTypes), hasExplicitTag);
    }
    writeSequenceOrSetToStringFunction(  className,componentTypes);
  }

  @Override
  protected void writeSetComponentDecodeRegular(ComponentInfo component, boolean first)
      throws IOException {

    String elseString = first ? "" : " else ";
    if (component.tag != null) {
      write(elseString + "if berTag.Equals(" + getBerTagParametersString(component.tag) + ") {");
    } else {
      write(elseString + "if (berTag.Equals(new(" + normaliseClassName(component.className) + ").GetTag())) {");
    }

    if (isExplicit(component.tag)) {
      write("n,err = length.Decode(is)");
      write("vByteCount += n");
      write("if err != nil {\n"
          + "\t\t\treturn 0, err\n"
          + "\t\t}");

    }

    write("b." + component.variableName + " = new (" + normaliseClassName(component.className) + ")");
    write(
        "n,err = b."
            + component.variableName
            + ".Decode" + getDecodeFuncSuffix(component) + "(is, "
            + getDecodeTagParameter(component)
            + ")");
    write("vByteCount += n");
    write("if err != nil {\n"
        + "\t\t\treturn 0, err\n"
        + "\t\t}");

    if (isExplicit(component.tag)) {
      write("n,err = length.ReadEocIfIndefinite(is)");
      write("vByteCount += n");
      write("if err != nil {\n"
          + "\t\t\treturn 0, err\n"
          + "\t\t}");
    }
    out.write("\n\t} "); // The 'else' in golang must be on same line...
  }

  @Override
  protected void writeSetDecodeFunction(String className, List<ComponentInfo> components, boolean hasExplicitTag)
      throws IOException {

    write("func (b *" + className + ") Decode(is io.Reader, withTagList ...bool) (int, error) {");
    write("var withTag bool\n"
        + "\tif len(withTagList) > 0 {\n"
        + "\t\twithTag = withTagList[0]\n"
        + "\t} else {\n"
        + "\t\twithTag = true\n"
        + "\t}\n");
    write("var err error\n"
        + "\tvar n int");
    write("tlByteCount := 0");
    write("vByteCount := 0");
    write("berTag := new(" + LIB_PREFIX + ".BerTag)\n");

    write("if withTag {");
    write("n,err = b.GetTag().decodeAndCheck(is)");
    write("tlByteCount += n");
    write("if err != nil {\n"
        + "\t\t\treturn 0, err\n"
        + "\t\t}");

    write("}\n");

    if (hasExplicitTag) {
      write("explicitTagLength := &" + LIB_PREFIX + ".BerLength{}");
      write("n,err = explicitTagLength.Decode(is)");
      write("tlByteCount += n");
      write("n,err = " + LIB_PREFIX + ".SET.DecodeAndCheck(is)\n");
      write("tlByteCount += n");
      write("if err != nil {\n"
          + "\t\t\treturn 0, err\n"
          + "\t\t}");
    }

    write("length := &" + LIB_PREFIX + ".BerLength{}");
    write("n,err = length.Decode(is)");
    write("tlByteCount += n");
    write("if err != nil {\n"
        + "\t\t\treturn 0, err\n"
        + "\t\t}");
    write("lengthVal = length.Length\n");

    if (allOptionalOrDefault(components)) {
      write("if lengthVal == 0 {");
      write("return tlByteCount,nil");
      write("}\n");
    }

    write("for (vByteCount < lengthVal || lengthVal < 0) {");
    write("n,err = berTag.Decode(is);");
    write("vByteCount += n");

    boolean first = true;
    for (ComponentInfo component : components) {
      if (component.isDirectChoiceOrAny && (component.tag == null)) {
        throw new IOException("choice or ANY within set has no explicit tag.");
      } else {
        writeSetComponentDecodeRegular(component, first);
      }
      first = false;
    }

    write("else if lengthVal < 0 && berTag.Equals(0, 0, 0)) {");
    write("err = " + LIB_PREFIX + ". ReadEocByte(is)");
    write("vByteCount += 1");
    write("if err != nil {\n"
        + "\t\t\treturn 0, err\n"
        + "\t\t}");

    if (hasExplicitTag) {
      write("n,err = explicitTagLength.ReadEocIfIndefinite(is)");
      write("vByteCount += n");
    }
    write("return tlByteCount + vByteCount,err");
    write("} else {");
    write("return 0,  errors.New(\"tag does not match any set component: \" + berTag)");
    write("}");

    write("}");

    write("if (vByteCount != lengthVal) {");
    write(
        "return 0,errors.New  (fmt.Sprintf(\"Length of set does not match length tag, length tag: %d, actual set length: %d \",  lengthVal, vByteCount))");
    write("}");
    if (hasExplicitTag) {
      write("n,err = explicitTagLength.ReadEocIfIndefinite(is)");
      write("vByteCount += n");
    }

    write("return tlByteCount + vByteCount,err");
    write("}\n");
  }

  @Override
  protected void writeEncodeTag(BerImplementationWriter.Tag tag) throws IOException {
    int typeStructure;

    if (tag.typeStructure == BerImplementationWriter.TypeStructure.CONSTRUCTED) {
      typeStructure = BerTag.CONSTRUCTED;
    } else {
      typeStructure = BerTag.PRIMITIVE;
    }

    BerTag berTag = new BerTag(getTagClassId(tag.tagClass.toString()), typeStructure, tag.value);

    write("// write tag: " + tag.tagClass + "_CLASS, " + tag.typeStructure + ", " + tag.value);
    for (int i = (berTag.tagBytes.length - 1); i >= 0; i--) {
      write("_,_ = " + LIB_PREFIX + ".WriteByte(reverseOS, 0x" + HexString.fromByte(berTag.tagBytes[i]) + ")");
    }

    write("codeLength += " + berTag.tagBytes.length + "");
  }

  @Override
  protected void writeSequenceOrSetEncodeFunction(
      String typeName, List<AsnElementType> componentTypes, boolean hasExplicitTag, boolean isSequence)
      throws IOException {
    write("func (b *" + typeName + ") Encode(reverseOS io.Writer, withTagList ...bool) (int, error) {");

    write("var withTag bool\n"
        + "\tif len(withTagList) > 0 {\n"
        + "\t\twithTag = withTagList[0]\n"
        + "\t} else {\n"
        + "\t\twithTag = true\n"
        + "\t}");

    write("codeLength := 0");
    write("var err error\n"
        + "\tvar n int");
    for (int j = componentTypes.size() - 1; j >= 0; j--) {
      if (isExplicit(getTag(componentTypes.get(j)))) {
        write("var sublength int\n");
        break;
      }
    }

    for (int j = componentTypes.size() - 1; j >= 0; j--) {

      AsnElementType componentType = componentTypes.get(j);

      BerImplementationWriter.Tag componentTag = getTag(componentType);

      if (isOptional(componentType)) {
        write("if b." + getVariableName(componentType) + " != nil {");
      }

      String explicitEncoding = getExplicitEncodingParameter(componentType);

      if (isExplicit(componentTag)) {
        write(
            "n,err = b."
                + getVariableName(componentType)
                + ".Encode(reverseOS"
                + explicitEncoding
                + ")");
        write("sublength += n");
        write("codeLength += sublength");
        write("if err != nil {\n"
            + "\t\t\treturn codeLength, err\n"
            + "\t\t}");
        write("n,err = " + LIB_PREFIX + ".EncodeLength(sublength,reversOS)");
      } else {
        write(
            "n,err = b."
                + getVariableName(componentType)
                + ".encode(reverseOS"
                + explicitEncoding
                + ");");
      }
      write("codeLength += n");
      write("if err != nil {\n"
          + "\t\t\treturn codeLength, err\n"
          + "\t\t}");

      if (componentTag != null) {
        writeEncodeTag(componentTag);
      }
      if (isOptional(componentType)) {
        write("}");
      }

      write("");
    }

    if (hasExplicitTag) {
      write("n,err = " + LIB_PREFIX + ".EncodeLength(codeLength,reverseOS)");
      write("codeLength += n");
      if (isSequence) {
        write("_,_  = " + LIB_PREFIX + ".WriteByte(reverseOS,0x30)");
      } else {
        write("_,_  = " + LIB_PREFIX + ".WriteByte(reverseOS,0x31)");
      }
      write("codeLength++\n");
    }

    write("n,err = " + LIB_PREFIX + ".EncodeLength(codeLength,reverseOS)\n");
    write("codeLength += n");
    write("if withTag {");
    write("n,err = b.GetTag().Encode(reverseOS)");
    write("codeLength += n");
    write("}\n");

    write("if err != nil {\n"
        + "\t\t\treturn codeLength, err\n"
        + "\t\t}");

    write("return codeLength,nil\n");

    write("}\n");
  }

  @Override
  protected void writeSequenceOfClass(
      String className,
      AsnSequenceOf asnSequenceOf,
      BerImplementationWriter.Tag tag,
      String isStaticStr,
      List<String> listOfSubClassNames)
      throws IOException {

    AsnElementType componentType = asnSequenceOf.componentType;

    String referencedTypeName = getClassNameOfSequenceOfElement(componentType, listOfSubClassNames);

    if (isInnerType(componentType)) {
      writeConstructedTypeClass(
          referencedTypeName, componentType.typeReference, null, true, listOfSubClassNames);
    }

    BerImplementationWriter.Tag mainTag = tagFromSequenceSet(tag, asnSequenceOf.isSequenceOf);

    write("type " + className + " struct {");
    write("seqOf []" + normaliseClassName(referencedTypeName));
    write("}");

    // Write tag func.
    write("func (b *" + className + ") GetTag () {");
    write("return " + LIB_PREFIX + ".NewBerTag(" + getBerTagParametersString(mainTag) + ")");
    write("}");

    boolean hasExplicitTag = (tag != null) && (tag.type == BerImplementationWriter.TagType.EXPLICIT);

    writeSequenceOfEncodeFunction(className, componentType, hasExplicitTag, asnSequenceOf.isSequenceOf);

    writeSequenceOrSetOfDecodeFunction(className,
        convertToComponentInfo(componentType, false, referencedTypeName),
        hasExplicitTag,
        asnSequenceOf.isSequenceOf);

    writeSequenceOrSetOfToStringFunction(className, referencedTypeName, componentType);
  }

  @Override
  protected void writeSequenceOfEncodeFunction(
      String className, AsnElementType componentType, boolean hasExplicitTag, boolean isSequence) throws IOException {

    write("func (b *" + className + ") Encode(reverseOS io.Writer, withTagList ...bool) (int, error) {");

    write("var withTag bool\n"
        + "\tif len(withTagList) > 0 {\n"
        + "\t\twithTag = withTagList[0]\n"
        + "\t} else {\n"
        + "\t\twithTag = true\n"
        + "\t}\n"
        + "\tcodeLength := 0");
    write("var err error\n"
        + "\tvar n int");

    write("for int i = len(b.seqOf) - 1; i >= 0; i-- {");

    BerImplementationWriter.Tag componentTag = getTag(componentType);
    String explicitEncoding = getExplicitEncodingParameter(componentType);

    if (componentTag != null) {

      if (componentTag.type == BerImplementationWriter.TagType.EXPLICIT) {
        write("sublength,err = b.seqOf[i].Encode(reverseOS" + explicitEncoding + ")");
        write("codeLength += sublength");
        write("n,err = " + LIB_PREFIX + ".EncodeLength( sublength, reverseOS)");

      } else {
        write("n,err = b.seqOf[i].Encode(reverseOS" + explicitEncoding + ")");
      }
      write("codeLength += n");
      write("if err != nil {\n"
          + "\t\t\treturn codeLength, err\n"
          + "\t\t}");
      writeEncodeTag(componentTag);
    } else {

      if (isDirectAnyOrChoice(componentType)) {
        write("n,err = b.seqOf[i].Encode(reverseOS)");
      } else {
        write("n,err = b.seqOf[i].Encode(reverseOS, true)");
      }
      write("codeLength += n");
      write("if err != nil {\n"
          + "\t\t\treturn codeLength, err\n"
          + "\t\t}");
    }

    write("}\n");

    if (hasExplicitTag) {
      write("n,err = " + LIB_PREFIX + ".EncodeLength( codeLength,reverseOS)");
      if (isSequence) {
        write("_,_ = " + LIB_PREFIX + ".WriteByte(reverseOS, 0x30)");
      } else {
        write("_,_ = " + LIB_PREFIX + ".WriteByte(reverseOS, 0x31)");
      }
      write("if err != nil {\n"
          + "\t\t\treturn codeLength, err\n"
          + "\t\t}");
      write("codeLength++;\n");
    }

    write("n,err = " + LIB_PREFIX + "b.EncodeLength(codeLength,reverseOS)\n");
    write("codeLength += n");
    write("if withTag {");
    write("n,err= b.GetTag().Encode(reverseOS)");
    write("codeLength += n");
    write("}\n");

    write("return codeLength,nil");
    write("}\n");
  }

  @Override
  protected void writeSequenceOrSetOfDecodeFunction(
      String className, ComponentInfo component, boolean hasExplicitTag, boolean isSequence) throws IOException {

    write("func (b *" + className + ") Decode(is io.Reader, withTagList ...bool) (int, error) {");
    write("var withTag bool\n"
        + "\tif len(withTagList) > 0 {\n"
        + "\t\twithTag = withTagList[0]\n"
        + "\t} else {\n"
        + "\t\twithTag = true\n"
        + "\t}\n"
        + "\tcodeLength := 0");
    write("var err error\n"
        + "\tvar n int");

    write("tlByteCount := 0");
    write("vByteCount := 0");
    if (containsUntaggedChoiceOrAny(Collections.singletonList(component))) {
      write("var numDecodedBytes int");
    }
    write("berTag := new (" + LIB_PREFIX + ".BerTag)");

    write("if withTag {");
    write("n,err = b.GetTag().DecodeAndCheck(is)");
    write("tlByteCount += n");
    write("if err != nil {\n"
        + "\t\t\treturn 0, err\n"
        + "\t\t}");
    write("}\n");

    if (hasExplicitTag) {
      write("explicitTagLength := &" + LIB_PREFIX + ".BerLength{}");
      write("n,err = explicitTagLength.Decode(is)");
      write("tlByteCount += n");
      write("if err != nil {\n"
          + "\t\t\treturn codeLength, err\n"
          + "\t\t}");
      if (isSequence) {
        write("n,err = " + LIB_PREFIX + ".SEQUENCE.DecodeAndCheck(is)\n");
      } else {
        write("n,err = " + LIB_PREFIX + ".SET.DecodeAndCheck(is)\n");
      }
      write("tlByteCount += n");
      write("if err != nil {\n"
          + "\t\t\treturn 0, err\n"
          + "\t\t}");
    }

    write("length := &" + LIB_PREFIX + ".BerLength{}");
    write("n,err = length.Decode(is)");
    write("tlByteCount += n");
    write("lengthVal := length.Length;\n");
    write("if err != nil {\n"
        + "\t\t\treturn 0, err\n"
        + "\t\t}");
    write("for (vByteCount < lengthVal || lengthVal < 0) {");
    write("n,err = berTag.Decode(is)\n");
    write("vByteCount += n");
    write("if lengthVal < 0 && berTag.equals(0, 0, 0) {");
    write("err = " + LIB_PREFIX + ".ReadEocByte(is)");
    write("vByteCount += 1");
    write("break;");
    write("}\n");

    if (component.isDirectChoiceOrAny && (component.tag == null)) {
      writeSequenceOfComponentDecodeUntaggedChoiceOrAny(component);
    } else {
      writeSequenceOfComponentDecodeRegular(component);
    }

    write("}");

    write("if lengthVal >= 0 && vByteCount != lengthVal {");
    write(
        "return 0, errors.New(fmt.Sprintf(\"Decoded SequenceOf or SetOf has wrong length. Expected %d but has %d \", lengthVal, +vByteCount ))\n");
    write("}");

    if (hasExplicitTag) {
      write("n,err = explicitTagLength.ReadEocIfIndefinite(is)");
      write("vByteCount += n");
    }
    write("return tlByteCount + vByteCount,err");
    write("}\n");
  }

  @Override
  protected void writeSequenceOfComponentDecodeUntaggedChoiceOrAny(ComponentInfo component)
      throws IOException {
    write("element := new(" + normaliseClassName(component.className) + ")");
    write("numDecodedBytes,err = " + "element.Decode" + getDecodeFuncSuffix(component) + "(is, " + getDecodeTagParameter(component) + ")");
    write("if (numDecodedBytes == 0) {");
    write("return 0,errors.New(\"tag did not match\")");
    write("}");
    write("vByteCount += numDecodedBytes");
    write("b.seqOf = append(b.sqIf,element)");
  }

  @Override
  protected void writeSequenceOfComponentDecodeRegular(ComponentInfo component) throws IOException {
    if (component.tag != null) {
      write("if !berTag.equals(" + getBerTagParametersString(component.tag) + ") {");
    } else {
      write("if (!berTag.EqualsTag(new(" + normaliseClassName(component.className) + ").GetTag()) {");
    }
    write("return 0, errors.New(\"tag does not match mandatory sequence of/set of component.\")");
    write("}");

    if (isExplicit(component.tag)) {
      write("n,err = length.Decode(is)");
      write("vByteCount += n");
    }
    write("element := new (" + normaliseClassName(component.className) + ")");
    write("n,err = " + "element.Decode" + getDecodeFuncSuffix(component) + "(is, " + getDecodeTagParameter(component) + ")");
    write("vByteCount += n");
    write("b.seqOf = append(b.seqOf,element)");
    write("if err != nil {\n"
        + "\t\t\treturn codeLength, err\n"
        + "\t\t}");
    if (isExplicit(component.tag)) {
      write("n,err = length.ReadEocIfIndefinite(is)");
      write("vByteCount += n");
      write("if err != nil {\n"
          + "\t\t\treturn codeLength, err\n"
          + "\t\t}");
    }
  }

  @Override
  protected void writeSequenceDecodeMethod(String className, List<ComponentInfo> components, boolean hasExplicitTag)
      throws IOException {
    write("func (b *" + className + ") Decode(is io.Reader, withTagList ...bool) (int, error) {");

    write("var withTag bool\n"
        + "\tif len(withTagList) > 0 {\n"
        + "\t\twithTag = withTagList[0]\n"
        + "\t} else {\n"
        + "\t\twithTag = true\n"
        + "\t}\n"
        + "\tcodeLength := 0");
    write("var err error\n"
        + "\tvar n int");

    write(" tlByteCount := 0");
    write(" vByteCount := 0");
    if (containsUntaggedChoiceOrAny(components)) {
      write("var numDecodedBytes int");
    }
    write("berTag := new(" + LIB_PREFIX + ".BerTag)\n");

    write("if withTag {");
    write("n,err = b.GetTag().decodeAndCheck(is);");
    write("tlByteCount += n");
    write("if err != nil {\n"
        + "\t\t\treturn codeLength, err\n"
        + "\t\t}");
    write("}\n");

    if (hasExplicitTag) {
      write("explicitTagLength := &" + LIB_PREFIX + ". BerLength{}");
      write("n,err = explicitTagLength.Decode(is)");
      write("tlByteCount += n");
      write("n,err =  " + LIB_PREFIX + ".SEQUENCE.DecodeAndCheck(is)\n");
      write("tlByteCount += n");
      write("if err != nil {\n"
          + "\t\t\treturn codeLength, err\n"
          + "\t\t}");
    }

    write(" length := &" + LIB_PREFIX + ". BerLength{}");
    write("n,err = length.Decode(is)");
    write("tlByteCount += n");
    write("lengthVal := length.Length");

    if (allOptionalOrDefault(components)) {
      write("if lengthVal == 0 {");
      write("return tlByteCount,nil");
      write("}");
    }
    write("n,err = berTag.Decode(is)\n");
    write("vByteCount += n");
    write("if err != nil {\n"
        + "\t\t\treturn codeLength, err\n"
        + "\t\t}");

    for (ComponentInfo component : components) {
      if (component.isDirectChoiceOrAny && (component.tag == null)) {
        writeSequenceComponentDecodeUntaggedChoiceOrAny(component);
      } else {
        writeSequenceComponentDecodeRegular(component);
        write("");
      }
    }

    if (extensibilityImplied) {
      writeSequenceDecodeMethodExtensibleEnd(hasExplicitTag);
    } else {
      writeSequenceDecodeMethodNonExtensibleEnd(hasExplicitTag);
    }

    write("}\n");
  }

  @Override
  protected void writeSequenceDecodeMethodExtensibleEnd(boolean hasExplicitTag) throws IOException {
    write("if lengthVal < 0 {");
    write("for (!berTag.equals(0, 0, 0)) {");
    write("n,err = " + LIB_PREFIX + ". DecodeUnknownComponent(is)");
    write("if err != nil {\n"
        + "\t\t\treturn 0, err\n"
        + "\t\t}");
    write("vByteCount += n");
    write("n,err = berTag.Decode(is)");
    write("vByteCount += n");
    write("}");

    write("_ =  " + LIB_PREFIX + ".  ReadEocByte(is)");
    write("vByteCount += 1");
    if (hasExplicitTag) {
      write("n,err = explicitTagLength.ReadEocIfIndefinite(is)");
      write("vByteCount += n");
      write("if err != nil {\n"
          + "\t\t\treturn 0, err\n"
          + "\t\t}");
    }
    write("return tlByteCount + vByteCount,nil");
    write("} else {");
    write("for (vByteCount < lengthVal) {");
    write("n,err = " + LIB_PREFIX + ". DecodeUnknownComponent(is)");
    write("vByteCount += n");
    write("if err != nil {\n"
        + "\t\t\treturn 0, err\n"
        + "\t\t}");
    write("if vByteCount == lengthVal {");
    write("return tlByteCount + vByteCount,nil");
    write("}");
    write("n,err = berTag.decode(is)");
    write("vByteCount += n");
    write("if err != nil {\n"
        + "\t\t\treturn 0, err\n"
        + "\t\t}");
    write("}");
    write("}");
    write(
        "return 0,errors.New(fmt.Sprintf(\"unexpected end of sequence, length tag: %d, bytes decoded: %d\", lengthVal, vByteCount))");
  }

  private String getDecodeFuncSuffix(ComponentInfo component) {
    if (component.isDirectChoiceOrAny) {
      return "WithTag";
    }
    return "";
  }

  @Override
  protected void writeSequenceComponentDecodeUntaggedChoiceOrAny(ComponentInfo component)
      throws IOException {
    write("b." + component.variableName + " = new (" + normaliseClassName(component.className) + ")");
    write(
        "numDecodedBytes,_ = b."
            + component.variableName
            + ".Decode" + getDecodeFuncSuffix(component) + " (is, "
            + getDecodeTagParameter(component)
            + ")");

    write("if numDecodedBytes != 0 {");
    write("vByteCount += numDecodedBytes");

    if (component.mayBeLast) {
      writeReturnIfDefiniteLengthMatchesDecodedBytes();
    }
    write("n,err = berTag.Decode(is)");
    write("vByteCount += n");
    write("if err != nil {\n"
        + "\t\t\treturn 0, err\n"
        + "\t\t}");
    write("}");
    if (component.isOptionalOrDefault) {
      write("else {");
      write("b." + component.variableName + " = nil");
      write("}");
    } else {
      writeElseThrowTagMatchingException();
    }
  }

  @Override
  protected void writeSequenceComponentDecodeRegular(ComponentInfo component) throws IOException {

    if (component.tag != null) {
      write("if (berTag.Equals(" + getBerTagParametersString(component.tag) + ")) {");
    } else {
      write("if (berTag.EqualsTag(" + component.className + ".GetTag())) {");
    }

    if (isExplicit(component.tag)) {
      write("n,_ = length.Decode(is)");
      write("vByteCount += n");
    }

    write("b." + component.variableName + " = new (" + normaliseClassName(component.className) + ");");
    write(
        "n,err = b."
            + component.variableName
            + ".Decode " + getDecodeFuncSuffix(component) + "(is, "
            + getDecodeTagParameter(component)
            + ")");
    write("vByteCount += n");
    write("if err != nil {\n"
        + "\t\t\treturn 0, err\n"
        + "\t\t}");
    if (isExplicit(component.tag)) {
      write("n,err = length.ReadEocIfIndefinite(is)");
      write("vByteCount += n");
      write("if err != nil {\n"
          + "\t\t\treturn 0, err\n"
          + "\t\t}");
    }

    if (component.mayBeLast) {
      writeReturnIfDefiniteLengthMatchesDecodedBytes();
    }
    write("n,err = berTag.decode(is);");
    write("vByteCount += n");
    write("if err != nil {\n"
        + "\t\t\treturn 0, err\n"
        + "\t\t}");
    write("}");
    if (!component.isOptionalOrDefault) {
      writeElseThrowTagMatchingException();
    }
  }

  @Override
  protected void writeSequenceDecodeMethodNonExtensibleEnd(boolean hasExplicitTag)
      throws IOException {
    write("if lengthVal < 0 {");
    write("if !berTag.Equals(0, 0, 0) {");
    write("return 0,errors.New(\"decoded sequence has wrong end of contents octets\")");
    write("}");
    write("n,err =  " + LIB_PREFIX + ".ReadEocByte(is)");
    write("vByteCount += n");
    write("if err != nil {\n"
        + "\t\t\treturn 0, err\n"
        + "\t\t}");
    if (hasExplicitTag) {
      write("n,err = explicitTagLength.ReadEocIfIndefinite(is)");
      write("vByteCount += n");
    }
    write("return tlByteCount + vByteCount,err");
    write("}\n");

    write(
        "return 0,errors.New(fmt.Sprintf(\"unexpected end of sequence, length tag: %d , bytes decoded: %d\",  lengthVal , vByteCount))\n");
  }

  @Override
  protected void writeElseThrowTagMatchingException() throws IOException {
    write("else {");
    write(" return 0,errors.New(\"tag does not match mandatory sequence component.\")");
    write("}");
  }

  @Override
  protected void writeReturnIfDefiniteLengthMatchesDecodedBytes() throws IOException {
    write("if lengthVal >= 0 && vByteCount == lengthVal {");
    write("return tlByteCount + vByteCount,nil");
    write("}");
  }

  @Override

  protected void writeToStringFunction(String className) throws IOException {
    write("func(b * " + className + ") S() string {");
    write("var sb bytes.Buffer");
    write("b.AppendAsString(sb, 0)");
    write("return sb.String()");
    write("}\n");
  }

  @Override
  protected void writeChoiceToStringFunction(String className, List<AsnElementType> componentTypes) throws IOException {
    writeToStringFunction(className);

    write("func (b * " + className + ")  AppendAsString( sb bytes.Buffer,   indentLevel int) {\n");

    for (AsnElementType componentType : componentTypes) {
      write("if b." + getVariableName(componentType) + " != nil {");

      if (!isPrimitive(getUniversalType(componentType))) {
        write("sb.WriteString(\"" + getVariableName(componentType) + ": \")");
        write("b." + getVariableName(componentType) + ".AppendAsString(sb, indentLevel + 1)");
      } else {
        write(
            "sb.WriteString(\""
                + getVariableName(componentType)
                + ": \")\n\tsb.WriteString(b."
                + getVariableName(componentType)
                + ".S());");
      }
      write("}\n");
    }

    write("sb.WriteString(\"<none>\");");

    write("}\n");
  }


  protected void writeSequenceOrSetToStringFunction(String className, List<AsnElementType> componentTypes)
      throws IOException {

    writeToStringFunction(className);
    write("func (b * " + className + ")  AppendAsString( sb bytes.Buffer,   indentLevel int) {\n");


    write("sb.WriteString(\"{\");");

    boolean checkIfFirstSelectedElement = componentTypes.size() > 1;

    int j = 0;

    for (AsnElementType componentType : componentTypes) {

      if (isOptional(componentType)) {
        if (j == 0 && componentTypes.size() > 1) {
          write(" firstSelectedElement := true");
        }
        write("if b." + getVariableName(componentType) + " != nil {");
      }

      if (j != 0) {
        if (checkIfFirstSelectedElement) {

          write("if !firstSelectedElement {");
        }
        write("sb.WriteString(\",\\n\")");
        if (checkIfFirstSelectedElement) {
          write("}");
        }
      } else {
        write("sb.WriteString(\"\\n\")");
      }

      write("for  i := 0; i < indentLevel + 1; i++ {");
      write("sb.WriteString(\"\\t\");");
      write("}");
      if (!isOptional(componentType)) {
        write("if b." + getVariableName(componentType) + " != nil {");
      }
      if (!isPrimitive(getUniversalType(componentType))) {
        write("sb.WriteString(\"" + getVariableName(componentType) + ": \");");
        write("b." +getVariableName(componentType) + ".AppendAsString(sb, indentLevel + 1)");
      } else {
        write(
            "sb.WriteString(\""
                + getVariableName(componentType)
                + ": \")");
         write(" sb.WriteString(b."
                + getVariableName(componentType)
                + ".S())");
      }
      if (!isOptional(componentType)) {
        write("} else {");
        write("sb.WriteString(\"" + getVariableName(componentType) + ": <empty-required-field>\")");
        write("}");
      }

      if (isOptional(componentType)) {
        if (checkIfFirstSelectedElement && j != (componentTypes.size() - 1)) {
          write("firstSelectedElement := false");
        }
        write("}");
      } else {
        checkIfFirstSelectedElement = false;
      }

      write("");

      j++;
    }

    write("sb.WriteString(\"\\n\")");
    write("for i := 0; i < indentLevel; i++ {");
    write("sb.WriteString(\"\\t\")");
    write("}");
    write("sb.WriteString(\"}\")");

    write("}\n");
  }

  @Override
  protected void writeSequenceOrSetOfToStringFunction(
      String className, String referencedTypeName, AsnElementType componentType) throws IOException {

    writeToStringFunction(className);

    write("func (b * " + className + ")  AppendAsString( sb bytes.Buffer,   indentLevel int) {\n");

    write("sb.WriteString(\"{\\n\");");
    write("for int i := 0; i < indentLevel + 1; i++ {");
    write("sb.WriteString(\"\\t\");");
    write("}");

    write("if b.seqOf == nil {");
    write("sb.WriteString(\"null\");");
    write("} else {");

    write("for _, element : range b.seqOf  {");

    if (!isPrimitive(getUniversalType(componentType))) {
      write("element.AppendAsString(sb, indentLevel + 1)");
    } else {
      write("sb.WriteString(element.S())");
    }
    write("sb.WriteString(\",\\n\");");
    write("for  i := 0; i < indentLevel + 1; i++ {");
    write("sb.WriteString(\"\\t\");");
    write("}");

    write("} ");



    write("}\n");

    write("sb.WriteString(\"\\n\");");
    write("for  i := 0; i < indentLevel; i++ {");
    write("sb.WriteString(\"\\t\");");
    write("}");
    write("sb.WriteString(\"}\");");

    write("}\n");
  }
}